---
name: "IMVDb"
guid: "e29621a5-fa9e-4330-982e-ef6e54c0cad2"
version: "1.0.0.0"
targetAbi: "10.6.0.0"
owner: "crobibero"
overview: "Get Music Video metadata from IMVDb"
description: >
  Get Music Video metadata from IMVDb
category: "Metadata"
artifacts:
- "Jellyfin.Plugins.IMVDb.dll"
changelog: >
  changelog
